export const defaultAmenities = [
  {
    title: 'Pool',
    hours: '6:00 AM - 10:00 PM',
    description: 'Infinity-edge pool with sunset deck.',
    imageUrl: 'https://picsum.photos/seed/amenity-pool/1000/600',
    order: 0,
    isActive: true,
  },
  {
    title: 'Spa',
    hours: '8:00 AM - 11:00 PM',
    description: 'Holistic wellness therapies and steam lounge.',
    imageUrl: 'https://picsum.photos/seed/amenity-spa/1000/600',
    order: 1,
    isActive: true,
  },
  {
    title: 'Restaurant',
    hours: '24 Hours',
    description: 'Multi-cuisine fine dining with chef tasting menus.',
    imageUrl: 'https://picsum.photos/seed/amenity-restaurant/1000/600',
    order: 2,
    isActive: true,
  },
  {
    title: 'Gym',
    hours: '24 Hours',
    description: 'Premium equipment and private trainer sessions.',
    imageUrl: 'https://picsum.photos/seed/amenity-gym/1000/600',
    order: 3,
    isActive: true,
  },
  {
    title: 'Bar',
    hours: '5:00 PM - 1:00 AM',
    description: 'Craft cocktails and rare cellar selections.',
    imageUrl: 'https://picsum.photos/seed/amenity-bar/1000/600',
    order: 4,
    isActive: true,
  },
  {
    title: 'Concierge',
    hours: '24 Hours',
    description: 'Personalized city and travel experiences.',
    imageUrl: 'https://picsum.photos/seed/amenity-concierge/1000/600',
    order: 5,
    isActive: true,
  },
];

export const defaultGalleryImages = [
  { category: 'Rooms', imageUrl: 'https://picsum.photos/seed/rooms-1/700/900', title: 'Rooms 1', order: 0, isActive: true },
  { category: 'Rooms', imageUrl: 'https://picsum.photos/seed/rooms-2/700/900', title: 'Rooms 2', order: 1, isActive: true },
  { category: 'Rooms', imageUrl: 'https://picsum.photos/seed/rooms-3/700/900', title: 'Rooms 3', order: 2, isActive: true },
  { category: 'Pool', imageUrl: 'https://picsum.photos/seed/pool-1/700/900', title: 'Pool 1', order: 0, isActive: true },
  { category: 'Pool', imageUrl: 'https://picsum.photos/seed/pool-2/700/900', title: 'Pool 2', order: 1, isActive: true },
  { category: 'Restaurant', imageUrl: 'https://picsum.photos/seed/restaurant-1/700/900', title: 'Restaurant 1', order: 0, isActive: true },
  { category: 'Restaurant', imageUrl: 'https://picsum.photos/seed/restaurant-2/700/900', title: 'Restaurant 2', order: 1, isActive: true },
  { category: 'Events', imageUrl: 'https://picsum.photos/seed/events-1/700/900', title: 'Events 1', order: 0, isActive: true },
  { category: 'Events', imageUrl: 'https://picsum.photos/seed/events-2/700/900', title: 'Events 2', order: 1, isActive: true },
  { category: 'Exterior', imageUrl: 'https://picsum.photos/seed/exterior-1/700/900', title: 'Exterior 1', order: 0, isActive: true },
  { category: 'Exterior', imageUrl: 'https://picsum.photos/seed/exterior-2/700/900', title: 'Exterior 2', order: 1, isActive: true },
  { category: 'Exterior', imageUrl: 'https://picsum.photos/seed/exterior-3/700/900', title: 'Exterior 3', order: 2, isActive: true },
];